# ─── Plugins (via TPM) ────────────────────────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'rose-pine/tmux'

# ─── General ──────────────────────────────────────────────────────────────────
set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",tmux-256color:RGB"

set -g set-clipboard on
set -g allow-passthrough on
set -as terminal-features ',xterm-256color:clipboard'

# ─── Prefix ───────────────────────────────────────────────────────────────────
unbind C-b
set -g prefix C-SPACE
bind C-SPACE send-prefix

# ─── Keymapping ───────────────────────────────────────────────────────────────
bind v split-window -h -c "#{pane_current_path}"
bind V split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5
bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5

# ─── Rose Pine Theme ──────────────────────────────────────────────────────────
set -g @rose_pine_variant 'moon'  # main | moon | dawn

# ─── Continuum Settings ───────────────────────────────────────────────────────
#set -g @continuum-restore 'on'
#set -g @Continuum-save-interval '5'

# ─── Status bar ───────────────────────────────────────────────────────────────
set -g @rose_pine_host 'on'
set -g @rose_pine_hostname_short 'on'
set -g @rose_pine_user 'on'
set -g @rose_pine_directory 'on'
set -g @rose_pine_date_time '%d.%m. %H:%M'

# Automatically set window name to current directory
# set -g automatic-rename 'on'
# set -g automatic-rename-format '#{b:pane_current_path}'

# Separators
set -g @rose_pine_left_separator ' > '
set -g @rose_pine_right_separator ' < '
set -g @rose_pine_field_separator '  '
set -g @rose_pine_window_separator ': '
set -g @rose_pine_window_status_separator " | "

# Icons
set -g @rose_pine_session_icon ''
set -g @rose_pine_current_window_icon ''
set -g @rose_pine_folder_icon ''
set -g @rose_pine_username_icon ''
set -g @rose_pine_hostname_icon '󰒋'
set -g @rose_pine_date_time_icon ''

# ─── Other settings ───────────────────────────────────────────────────────────
set -sg escape-time 0 # Delay after pressing the ESC key

# ─── Initialize TPM (must be at the end) ──────────────────────────────────────
run '~/.tmux/plugins/tpm/tpm'
